import Foundation

struct Strings {
    static let Call = "Call"
    static let Account = "Account"
    static let EnterLogin = "Enter login"
    static let EnterPassword = "Enter password"
    static let Activate = "Activate"
    static let Deactivate = "Deactivate"
    static let PushTokenDescription = "Push token (tap to copy to clipboard):"
    static let PushTokenCopyConfirmation = "Push token copied to clipboard"
    static let SendLogs = "Send logs"
    static let CallReject = "Reject"
    static let CallTerminate = "Terminate"
    static let CallAnswer = "Answer"
    static let CallHold = "Hold"
    static let CallResume = "Resume"
    static let CallMute = "Mute"
    static let Dtmf = "DTMF"
    static let AudioRoute = "Audio Route"
    static let Add = "Add"
    static let CallTransfer = "Transfer"
    static let HeavyAsterisk = "\u{2731}"
    static let SmallAsterisk = "\u{FE61}"
    static let RegistrationState = "Registration state:"
    static let BackToCall = "Back to call"
    static let CallLocation = "Call location"
    static let NotificationOpenAppTitle = "Action required"
    static let NotificationOpenAppBody = "Open the app to accept a call"
    static let CallsActionConference = "Сombine calls"
    static let CallsActionConferenceHint = "Create a conference"
    static let CallsActionTransfer = "Transfer call"
    static let CallsActionTransferHint = "Merge calls and leave conversation"
    static let ClearLogsTitle = "Clear logs"
    static let ClearLogsMessage = "Do you want to remove old log files?"
    static let ClearLogsConfirm = "Confirm"
    static let ClearLogsCancel = "Cancel"
}

struct Images {
    static let CallCircle = "phone.down.circle"
    static let AccountCircle = "person.circle"
    static let CallMute = "mic.slash"
    static let CallReject = "xmark"
    static let CallTerminate = "phone.down.fill"
    static let CallAnswer = "checkmark"
    static let CallHold = "pause.fill"
    static let CallResume = "phone.fill"
    static let CallActive = "speaker.wave.3"
    static let CallLostConnection = "wifi.slash"
    static let Pause = "pause"
    static let CallMuteFill = "mic.slash.fill"
    static let Keys3x3 = "square.grid.3x3"
    static let Speaker = "speaker"
    static let Add = "plus"
    static let CallTransfer = "arrow.left.arrow.right"
    static let Play = "play"
    static let Close = "xmark.circle"
    static let Backspace = "delete.left"
    static let InfoCircle = "info.circle"
    static let Back = "arrow.backward"
    static let Contacts = "person.crop.circle"
}

